In [29]:
import numpy as np

In [30]:
A=np.matrix('1 2; 4 -1')
B=np.matrix('2 -3;-4 1')
C=A*B-B*A

print(C)

[[ 4 -8]
 [12 -4]]


In [31]:
A=np.matrix('-1 2; 0 1')
A_2=A**2

print(A_2)

[[1 0]
 [0 1]]


In [32]:
A=np.matrix('3 5; 6 -1')
B=np.matrix('2 1; -3 2')
C=A*B

print(C)

[[-9 13]
 [15  4]]


In [33]:
A=np.matrix('2 3 4; 1 0 6; 7 8 9')

print(format(np.linalg.det(A), '.9g'))

35


In [34]:
A=np.matrix('1 2 3 4; -2 1 -4 3; 3 -4 -1 2; 4 3 -2 -1')

print(format(np.linalg.det(A), '.9g'))

900


In [35]:
A=np.matrix('1 2 -3; 0 1 2; 0 0 1')

print(np.linalg.inv(A))

[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [36]:
A=np.matrix('1 2 3 4; 3 -1 2 5; 1 2 3 4; 1 3 4 5')

print(np.linalg.matrix_rank(A))

2


In [37]:
A=np.matrix('2 -1 1; 3 4 -2; 1 -3 1')
B=np.matrix('5;-3; 4')
A_inv=np.linalg.inv(A)
X=A_inv.dot(B)

print('  x=\n',X.round(3))

  x=
 [[ 1.]
 [-0.]
 [ 3.]]


In [38]:
A = np.matrix('2 -1 1; 3 4 -2; 1 -3 1')
B = np.matrix('5; -3; 4')

def kramer(A, B):
    det_A=np.linalg.det(A)
    if det_A!=0:
        A1=np.matrix(A)
        A2=np.matrix(A)
        A3=np.matrix(A)
        A1[:,0]=B
        A2[:,1]=B
        A3[:,2]=B
        x=np.linalg.det(A1)/det_A
        y=np.linalg.det(A2)/det_A
        z=np.linalg.det(A3)/det_A
        print('x=', x.round(3), 'y=', y.round(3), 'z=', z.round(3))
    else:
        print('Визначник дорівнює нулю, система не має розвязків')
    return x, y, z
kramer(A, B)

x= 1.0 y= 0.0 z= 3.0


(1.0000000000000004, 5.828670879282059e-16, 3.0)

In [39]:
A = np.matrix('2 -1 1; 3 4 -2; 1 -3 1')
B = np.matrix('5; -3; 4')

def kramer(A, B):
    det_A=np.linalg.det(A)
    if det_A!=0:
        A1=np.matrix(A)
        A2=np.matrix(A)
        A3=np.matrix(A)
        A1[:,0]=B
        A2[:,1]=B
        A3[:,2]=B
        x=np.linalg.det(A1)/det_A
        y=np.linalg.det(A2)/det_A
        z=np.linalg.det(A3)/det_A
        print('x=', x.round(3), 'y=', y.round(3), 'z=', z.round(3))
    else:
        print('Визначник дорівнює нулю, система не має розвязків')
    return x, y, z
kramer(A, B)

x= 1.0 y= 0.0 z= 3.0


(1.0000000000000004, 5.828670879282059e-16, 3.0)

In [40]:
print('Перевірка:\n', np.linalg.solve(A,B).round(3))

Перевірка:
 [[ 1.]
 [-0.]
 [ 3.]]


In [100]:
import numpy as np

n = np.random.randint(1, 10)
m = np.random.randint(1, 10)
mat = np.random.randint(-10, 10, size=(n, m))
print('Згенерована матриця:\n', mat)

row_neg = np.sum(mat < 0, axis=1)
col_neg = np.sum(mat < 0, axis=0)

print("\nКількість негативних елементів в кожному рядку:")
for i in range(n):
    print(f"Рядок {i + 1}: {row_neg[i]}")

print("\nКількість негативних елементів в кожному стовпці:")
for j in range(m):
    print(f"Стовпець {j + 1}: {col_neg[j]}")

Згенерована матриця:
 [[  3   8]
 [  2  -5]
 [  4   2]
 [  1   0]
 [ -7  -8]
 [  4 -10]]

Кількість негативних елементів в кожному рядку:
Рядок 1: 0
Рядок 2: 1
Рядок 3: 0
Рядок 4: 0
Рядок 5: 2
Рядок 6: 1

Кількість негативних елементів в кожному стовпці:
Стовпець 1: 1
Стовпець 2: 3
